# Generated by Django 5.2.15 on 2026-06-28 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nom')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='montant cible')),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='montant actuel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'objectif',
                'verbose_name_plural': 'objectifs',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'name'), name='unique_goal_per_user')],
            },
        ),
    ]
