# Generated by Django 5.2.15 on 2026-06-28 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expenses', '0002_expense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('mock', 'Sandbox (mock)'), ('gocardless', 'GoCardless (Nordigen)'), ('bridge', 'Bridge')], default='mock', max_length=20, verbose_name='fournisseur')),
                ('external_id', models.CharField(blank=True, default='', max_length=128, verbose_name='id fournisseur')),
                ('status', models.CharField(choices=[('active', 'Active'), ('disconnected', 'Déconnectée')], default='active', max_length=20, verbose_name='statut')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='dernière synchro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_connections', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'connexion bancaire',
                'verbose_name_plural': 'connexions bancaires',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128, verbose_name='nom')),
                ('iban_masked', models.CharField(blank=True, default='', max_length=64, verbose_name='IBAN masqué')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='solde')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='devise')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='banking.bankconnection')),
            ],
            options={
                'verbose_name': 'compte bancaire',
                'verbose_name_plural': 'comptes bancaires',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('connection', 'external_id'), name='unique_account_per_connection')],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=128)),
                ('date', models.DateField(verbose_name='date')),
                ('description', models.CharField(max_length=200, verbose_name='libellé')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='montant signé')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='banking.bankconnection')),
                ('expense', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_transaction', to='expenses.expense')),
            ],
            options={
                'verbose_name': 'transaction bancaire',
                'verbose_name_plural': 'transactions bancaires',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('connection', 'external_id'), name='unique_banktx_per_connection')],
            },
        ),
    ]
